homepage:
    pattern:    /
    default: { _controller: AcmeComicalBundle:Reservation:index }

AcmeComicalBundle:
    resource: "@AcmeComicalBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
